import { db } from './db';
import { registry } from './bot-runtime';
import { realtime } from './events';
import { ActionType, TriggerType } from '@prisma/client';

function value(payload:any, field:string): string { return String(field.split('.').reduce((v,k)=>v?.[k],payload) ?? ''); }
function matches(operator:string, actual:string, expected:string) { switch(operator){case 'equals':return actual===expected;case 'not_equals':return actual!==expected;case 'contains':return actual.includes(expected);case 'not_contains':return !actual.includes(expected);case 'starts_with':return actual.startsWith(expected);case 'ends_with':return actual.endsWith(expected);case 'greater_than':return Number(actual)>Number(expected);case 'less_than':return Number(actual)<Number(expected);default:return false;} }
export async function runAutomation(automation:any,payload:any){const context={...payload,event:payload};if(automation.conditions?.some((c:any)=>!matches(c.operator,value(context,c.field),c.value)))return {status:'SKIPPED'};const execution=await db.automationExecution.create({data:{automationId:automation.id,status:'RUNNING'}});try{const runtime=registry.get(automation.botId);for(const action of (automation.actions||[]).sort((a:any,b:any)=>a.order-b.order)){if(action.delay)await new Promise(r=>setTimeout(r,Math.min(action.delay,300000)));const text=String(action.value||'').replace(/\{\{([^}]+)\}\}/g,(_:string,k:string)=>value(context,k.trim()));switch(action.type as ActionType){case 'SEND_CHAT':runtime?.sendChat(text);break;case 'EXECUTE_COMMAND':runtime?.executeCommand(text);break;case 'START_BOT':{const b=await db.bot.findUnique({where:{id:automation.botId},include:{server:true}});if(b)await registry.start(b);break;}case 'STOP_BOT':await registry.stop(automation.botId);break;case 'RESTART_BOT':{const r=registry.get(automation.botId);if(r)await r.restart();break;}case 'SEND_NOTIFICATION':{const b=await db.bot.findUnique({where:{id:automation.botId},include:{server:true}});if(b)await db.notification.create({data:{userId:b.server.userId,botId:b.id,type:'AUTOMATION',title:automation.name,message:text}});break;}case 'DELAY':break;}}const done=await db.automationExecution.update({where:{id:execution.id},data:{status:'SUCCESS'}});realtime.emit('event',{botId:automation.botId,type:'AUTOMATION_EXECUTED',data:done});return done;}catch(error){const done=await db.automationExecution.update({where:{id:execution.id},data:{status:'FAILED',error:String(error)}});realtime.emit('event',{botId:automation.botId,type:'AUTOMATION_FAILED',data:done});return done;}}
export async function dispatchAutomation(botId:string,trigger:TriggerType,payload:any={}){const list=await db.automation.findMany({where:{botId,enabled:true,trigger},include:{conditions:true,actions:true}});return Promise.all(list.map(a=>runAutomation(a,payload)));}
export async function runSchedule(schedule:any){const result=await dispatchAutomation(schedule.botId,TriggerType.SCHEDULE,{command:schedule.command,event:{type:'SCHEDULE'}});const next=new Date(Date.now()+Math.max(60000,(schedule.interval||1)*(schedule.type==='INTERVAL_HOURS'?3600000:60000)));await db.schedule.updateMany({where:{id:schedule.id,lockedAt:null},data:{lastRunAt:new Date(),nextRunAt:next,lockedAt:null}});return result;}
export function startScheduler(){setInterval(async()=>{const due=await db.schedule.findMany({where:{enabled:true,nextRunAt:{lte:new Date()},lockedAt:null},take:50});for(const schedule of due){const locked=await db.schedule.updateMany({where:{id:schedule.id,lockedAt:null},data:{lockedAt:new Date()}});if(locked.count)await runSchedule(schedule).catch(()=>undefined)}},15000).unref();}
