import { EventEmitter } from 'node:events';
import mineflayer, { Bot } from 'mineflayer';
import { pathfinder } from 'mineflayer-pathfinder';
import { db } from './db';
import { redact } from './encryption';
import { BotStatus, LogLevel, TriggerType } from '@prisma/client';
export type RuntimeEvent = { botId: string; type: string; data?: unknown };
export class BotRuntime extends EventEmitter {
  readonly runtimeId = crypto.randomUUID(); private bot?: Bot; private stopping = false; private retry = 0; private timers: NodeJS.Timeout[] = []; private startedAt?: number;
  constructor(public readonly botId: string, private readonly server: { host: string; port: number }, private readonly config: { username: string; version?: string | null; autoReconnect: boolean; maxRetries: number; reconnectDelay: number; settings?: any }) { super(); }
  private async state(status: BotStatus, error?: string) { await db.bot.update({ where: { id: this.botId }, data: { status, runtimeId: this.runtimeId, lastError: error ? redact(error) : undefined, ...(status === 'ONLINE' ? { lastOnlineAt: new Date() } : {}), ...(status === 'OFFLINE' || status === 'ERROR' ? { lastOfflineAt: new Date() } : {}) } }).catch(() => undefined); this.emit('status', { botId: this.botId, status }); }
  private async log(level: LogLevel, message: string, category = 'SYSTEM') { const safe = redact(message); const bot = await db.bot.findUnique({ where: { id: this.botId }, select: { serverId: true, server: { select: { userId: true } } } }); if (bot) await db.botLog.create({ data: { userId: bot.server.userId, serverId: bot.serverId, botId: this.botId, level, category, message: safe } }).catch(() => undefined); this.emit('log', { botId: this.botId, message: safe, level }); }
  async start() { if (this.bot || this.stopping) return; this.stopping = false; this.retry = 0; await this.connect(); }
  private async connect() { await this.state(this.retry ? 'RECONNECTING' : 'CONNECTING'); const version = this.config.version?.trim() || false; try { this.bot = mineflayer.createBot({ host: this.server.host, port: this.server.port, username: this.config.username, version, auth: (this.config.settings?.auth || 'offline') as any, checkTimeoutInterval: 120000 }); this.bot.loadPlugin(pathfinder); this.bind(this.bot); await this.state('STARTING'); } catch (e) { await this.failure(e); } }
  private bind(bot: Bot) { bot.once('spawn', async () => { this.retry = 0; this.startedAt = Date.now(); await this.state('ONLINE'); await this.log('INFO', `Spawned on ${this.server.host}:${this.server.port}`, 'CONNECTION'); this.emit('event', { botId: this.botId, type: TriggerType.BOT_ONLINE }); this.timers.push(setInterval(() => { if (bot.entity && this.config.settings?.antiAfk !== false) { try { bot.swingArm(); } catch {} } }, 30000)); }); bot.on('chat', async (username, message) => { if (username === bot.username) return; await db.chatMessage.create({ data: { botId: this.botId, player: username, message, direction: 'INBOUND' } }).catch(() => undefined); await this.log('INFO', `<${username}> ${message}`, 'CHAT'); this.emit('chat', { botId: this.botId, username, message }); this.emit('event', { botId: this.botId, type: TriggerType.CHAT_MESSAGE, data: { player: { name: username }, message } }); }); bot.on('playerJoined', p => this.emit('event', { botId: this.botId, type: TriggerType.PLAYER_JOIN, data: { player: { name: p.username, uuid: p.uuid } } })); bot.on('playerLeft', p => this.emit('event', { botId: this.botId, type: TriggerType.PLAYER_LEAVE, data: { player: { name: p.username, uuid: p.uuid } } })); bot.on('kicked', async reason => { await this.state('KICKED', String(reason)); await this.log('WARNING', `Kicked: ${String(reason)}`, 'CONNECTION'); this.emit('event', { botId: this.botId, type: TriggerType.BOT_KICKED, data: { reason: String(reason) } }); }); bot.on('error', e => this.failure(e)); bot.on('end', () => this.disconnect()); }
  private async failure(error: unknown) { const message = error instanceof Error ? error.message : String(error); await this.state('ERROR', message); await this.log('ERROR', message); this.emit('event', { botId: this.botId, type: TriggerType.BOT_ERROR, data: { reason: message } }); if (!this.stopping && this.config.autoReconnect && this.retry < this.config.maxRetries) { this.retry++; await db.bot.update({ where: { id: this.botId }, data: { reconnectCount: { increment: 1 } } }).catch(() => undefined); const delay = Math.min(this.config.reconnectDelay * 2 ** (this.retry - 1), 300000); this.timers.push(setTimeout(() => this.connect(), delay)); } }
  private async disconnect() { if (this.stopping) return; this.bot = undefined; await this.state('OFFLINE'); if (this.config.autoReconnect && this.retry < this.config.maxRetries) { this.retry++; const delay = Math.min(this.config.reconnectDelay * 2 ** (this.retry - 1), 300000); this.timers.push(setTimeout(() => this.connect(), delay)); } }
  async stop() { this.stopping = true; this.timers.splice(0).forEach(clearTimeout); await this.state('STOPPING'); try { this.bot?.quit('Stopped by user'); } catch {} this.bot = undefined; await this.state('OFFLINE'); }
  async restart() { await this.stop(); await this.start(); }
  sendChat(message: string) { if (!this.bot || !this.bot.entity) throw new Error('Bot is not online'); this.bot.chat(message); }
  executeCommand(command: string) { const clean = command.trim().replace(/^\//, ''); if (!clean || clean.length > 256 || /[\r\n]/.test(clean)) throw new Error('Invalid command'); this.sendChat('/' + clean); }
  status() { return { runtimeId: this.runtimeId, startedAt: this.startedAt, online: Boolean(this.bot?.entity) }; }
}
export class RuntimeRegistry { private runtimes = new Map<string, BotRuntime>(); get size() { return this.runtimes.size; } get(botId: string) { return this.runtimes.get(botId); } async start(bot: any) { if (this.runtimes.has(bot.id)) return this.runtimes.get(bot.id)!; const runtime = new BotRuntime(bot.id, { host: bot.server.host, port: bot.server.port }, bot); this.runtimes.set(bot.id, runtime); runtime.on('status', e => this.emit(e)); runtime.on('log', e => this.emit(e)); runtime.on('chat', e => this.emit(e)); runtime.on('event', e => this.emit(e)); await runtime.start(); return runtime; } async stop(botId: string) { const runtime = this.runtimes.get(botId); if (runtime) { await runtime.stop(); this.runtimes.delete(botId); } } async stopAll() { await Promise.all([...this.runtimes.keys()].map(id => this.stop(id))); } private emit(event: RuntimeEvent) { this.emitEvent(event); } emitEvent: (event: RuntimeEvent) => void = () => {}; }
export const registry = new RuntimeRegistry();
