import { Router, Response } from 'express';
import { z } from 'zod';
import { db } from '../lib/db';
import { requireAuth, AuthRequest, hashPassword, signUser, verifyPassword } from '../lib/auth';
import { registry } from '../lib/bot-runtime';
import { realtime } from '../lib/events';
import { encrypt } from '../lib/encryption';
import { runAutomation, runSchedule } from '../lib/automation';
import { testServerConnection } from '../lib/server-status';

const router = Router();
const id = z.string().min(1).max(128);
const serverInput = z.object({ name:z.string().trim().min(1).max(80), host:z.string().trim().min(1).max(255), port:z.coerce.number().int().min(1).max(65535).default(25565), edition:z.enum(['JAVA','BEDROCK','AUTO']).default('AUTO'), version:z.string().trim().max(40).optional(), settings:z.record(z.string(), z.unknown()).optional() });
const botInput = z.object({ name:z.string().trim().min(1).max(80), username:z.string().trim().min(1).max(32), minecraftVersion:z.string().trim().max(40).optional(), edition:z.enum(['JAVA','BEDROCK','AUTO']).optional(), autoReconnect:z.boolean().default(true), maxRetries:z.coerce.number().int().min(0).max(100).default(10), reconnectDelay:z.coerce.number().int().min(1000).max(300000).default(5000), startOnBoot:z.boolean().default(false), settings:z.record(z.string(), z.unknown()).optional() });
const automationInput = z.object({ name:z.string().trim().min(1).max(100), enabled:z.boolean().default(true), trigger:z.enum(['BOT_START','BOT_ONLINE','BOT_OFFLINE','BOT_RECONNECT','BOT_ERROR','BOT_KICKED','CHAT_MESSAGE','PLAYER_JOIN','PLAYER_LEAVE','AUTH_REQUIRED','AUTH_SUCCESS','AUTH_FAILED','COMMAND_EXECUTED','COMMAND_FAILED','SCHEDULE']), cooldown:z.coerce.number().int().min(0).max(86400).default(0), executionLimit:z.coerce.number().int().min(1).max(10000).default(100), maxDepth:z.coerce.number().int().min(1).max(20).default(5), conditions:z.array(z.object({field:z.string().min(1).max(80),operator:z.enum(['equals','not_equals','contains','not_contains','starts_with','ends_with','greater_than','less_than']),value:z.string().max(500),order:z.number().int().default(0)})).default([]), actions:z.array(z.object({type:z.enum(['SEND_CHAT','EXECUTE_COMMAND','SEND_NOTIFICATION','DELAY','START_BOT','STOP_BOT','RESTART_BOT']),value:z.string().max(1000).optional(),delay:z.number().int().min(0).max(300000).default(0),order:z.number().int().default(0)})).default([]) });
const scheduleInput = z.object({name:z.string().trim().min(1).max(100),enabled:z.boolean().default(true),type:z.enum(['INTERVAL_MINUTES','INTERVAL_HOURS','DAILY','WEEKLY','SPECIFIC']),interval:z.coerce.number().int().min(1).max(100000).optional(),weekday:z.coerce.number().int().min(0).max(6).optional(),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),command:z.string().trim().min(1).max(256),nextRunAt:z.coerce.date().optional()});
const ownerServer=(userId:string,serverId:string)=>db.server.findFirst({where:{id:serverId,userId}});
const ownerBot=(userId:string,botId:string)=>db.bot.findFirst({where:{id:botId,server:{userId}},include:{server:true}});
const ownerAutomation=(userId:string,botId:string,automationId:string)=>db.automation.findFirst({where:{id:automationId,botId,bot:{server:{userId}}},include:{conditions:true,actions:true}});
const ownerSchedule=(userId:string,botId:string,scheduleId:string)=>db.schedule.findFirst({where:{id:scheduleId,botId,bot:{server:{userId}}}});
const jsonError=(res:Response,error:unknown)=>res.status(error instanceof z.ZodError?400:500).json({error:error instanceof Error?error.message:'Request failed'});

router.post('/auth/register',async(req,res)=>{try{const p=z.object({email:z.string().email(),password:z.string().min(10),name:z.string().max(80).optional()}).parse(req.body);if(await db.user.findUnique({where:{email:p.email}}))return res.status(409).json({error:'Email already registered'});const u=await db.user.create({data:{email:p.email,passwordHash:await hashPassword(p.password),name:p.name}});res.status(201).json({user:{id:u.id,email:u.email,name:u.name},token:signUser(u.id)});}catch(e){jsonError(res,e)}});
router.post('/auth/login',async(req,res)=>{try{const p=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const u=await db.user.findUnique({where:{email:p.email}});if(!u?.passwordHash||!(await verifyPassword(p.password,u.passwordHash)))return res.status(401).json({error:'Invalid credentials'});res.json({user:{id:u.id,email:u.email,name:u.name},token:signUser(u.id)});}catch(e){jsonError(res,e)}});
router.use(requireAuth);
router.get('/me',async(req:AuthRequest,res)=>res.json(await db.user.findUnique({where:{id:req.user!.id},select:{id:true,email:true,name:true,image:true}})));
router.get('/dashboard',async(req:AuthRequest,res)=>{const where={server:{userId:req.user!.id}};const [servers,bots,online,errors]=await Promise.all([db.server.count({where:{userId:req.user!.id}}),db.bot.count({where}),db.bot.count({where:{...where,status:'ONLINE'}}),db.bot.count({where:{...where,status:'ERROR'}})]);res.json({servers,bots,onlineBots:online,offlineBots:bots-online,errors,runtimeCount:registry.size});});
router.get('/servers',async(req:AuthRequest,res)=>res.json(await db.server.findMany({where:{userId:req.user!.id},include:{bots:{select:{id:true,name:true,username:true,status:true,ping:true,reconnectCount:true,lastError:true}}},orderBy:{createdAt:'desc'}})));
router.post('/servers',async(req:AuthRequest,res)=>{try{const data=serverInput.parse(req.body);res.status(201).json(await db.server.create({data:{...data,userId:req.user!.id}}));}catch(e){jsonError(res,e)}});
router.post('/servers/test-connection',async(req:AuthRequest,res)=>{try{const p=serverInput.omit({name:true}).parse({name:'test',...req.body});res.json(await testServerConnection(p.host,p.port,p.edition,p.version));}catch(e){jsonError(res,e)}});
router.get('/servers/:serverId',async(req:AuthRequest,res)=>{const s=await ownerServer(req.user!.id,req.params.serverId);if(!s)return res.sendStatus(404);res.json(await db.server.findUnique({where:{id:s.id},include:{bots:true}}));});
router.patch('/servers/:serverId',async(req:AuthRequest,res)=>{if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);try{res.json(await db.server.update({where:{id:req.params.serverId},data:serverInput.partial().parse(req.body)}));}catch(e){jsonError(res,e)}});
router.delete('/servers/:serverId',async(req:AuthRequest,res)=>{if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);await Promise.all((await db.bot.findMany({where:{serverId:req.params.serverId},select:{id:true}})).map(b=>registry.stop(b.id)));await db.server.delete({where:{id:req.params.serverId}});res.sendStatus(204);});
router.get('/servers/:serverId/bots',async(req:AuthRequest,res)=>{if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);res.json(await db.bot.findMany({where:{serverId:req.params.serverId},orderBy:{createdAt:'desc'}}));});
router.post('/servers/:serverId/bots',async(req:AuthRequest,res)=>{if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);const count=await db.bot.count({where:{server:{userId:req.user!.id}}});if(count>=Number(process.env.MAX_BOTS_PER_USER||25))return res.status(429).json({error:'Bot limit reached'});try{res.status(201).json(await db.bot.create({data:{...botInput.parse(req.body),serverId:req.params.serverId}}));}catch(e){jsonError(res,e)}});
async function serverAll(req:AuthRequest,res:Response,action:'start'|'stop'|'restart'){if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);const bots=await db.bot.findMany({where:{serverId:req.params.serverId},include:{server:true}});await Promise.all(bots.map(b=>action==='stop'?registry.stop(b.id):action==='restart'&&registry.get(b.id)?registry.get(b.id)!.restart():registry.start(b)));res.json({count:bots.length,action});}
router.post('/servers/:serverId/bots/start',async(req,res)=>serverAll(req as AuthRequest,res,'start'));router.post('/servers/:serverId/bots/stop',async(req,res)=>serverAll(req as AuthRequest,res,'stop'));router.post('/servers/:serverId/bots/restart',async(req,res)=>serverAll(req as AuthRequest,res,'restart'));
router.get('/bots/:botId',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);res.json(b);});
router.patch('/bots/:botId',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);try{res.json(await db.bot.update({where:{id:req.params.botId},data:botInput.partial().parse(req.body)}));}catch(e){jsonError(res,e)}});
router.delete('/bots/:botId',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);await registry.stop(req.params.botId);await db.bot.delete({where:{id:req.params.botId}});res.sendStatus(204);});
async function control(req:AuthRequest,res:Response,action:'start'|'stop'|'restart'){const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);if(action==='stop')await registry.stop(b.id);else if(action==='restart'&&registry.get(b.id))await registry.get(b.id)!.restart();else await registry.start(b);res.json(await db.bot.findUnique({where:{id:b.id}}));}
router.post('/bots/:botId/start',(req,res)=>control(req as AuthRequest,res,'start'));router.post('/bots/:botId/stop',(req,res)=>control(req as AuthRequest,res,'stop'));router.post('/bots/:botId/restart',(req,res)=>control(req as AuthRequest,res,'restart'));
router.get('/bots/:botId/logs',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.botLog.findMany({where:{botId:req.params.botId},orderBy:{createdAt:'desc'},take:500})});
router.get('/bots/:botId/chat',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.chatMessage.findMany({where:{botId:req.params.botId},orderBy:{createdAt:'desc'},take:500})});
router.post('/bots/:botId/chat',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);try{const p=z.object({message:z.string().trim().min(1).max(256)}).parse(req.body);const r=registry.get(b.id);if(!r)return res.status(409).json({error:'Bot is offline'});r.sendChat(p.message);res.status(201).json(await db.chatMessage.create({data:{botId:b.id,player:b.username,message:p.message,direction:'OUTBOUND'}}));}catch(e){jsonError(res,e)}});
router.get('/bots/:botId/commands',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.commandExecution.findMany({where:{botId:req.params.botId},orderBy:{createdAt:'desc'},take:200})});
router.post('/bots/:botId/commands',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);try{const p=z.object({command:z.string().trim().min(1).max(256)}).parse(req.body);const row=await db.commandExecution.create({data:{botId:b.id,command:p.command,status:'PENDING'}});try{registry.get(b.id)?.executeCommand(p.command);res.status(201).json(await db.commandExecution.update({where:{id:row.id},data:{status:'SUCCESS',result:'Command sent'}}));}catch(e){res.status(409).json(await db.commandExecution.update({where:{id:row.id},data:{status:'FAILED',result:String(e)}}));}}catch(e){jsonError(res,e)}});

router.get('/bots/:botId/automations',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.automation.findMany({where:{botId:req.params.botId},include:{conditions:true,actions:true},orderBy:{createdAt:'desc'}}));});
router.post('/bots/:botId/automations',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);try{const p=automationInput.parse(req.body);res.status(201).json(await db.automation.create({data:{name:p.name,enabled:p.enabled,trigger:p.trigger,cooldown:p.cooldown,executionLimit:p.executionLimit,maxDepth:p.maxDepth,botId:req.params.botId,conditions:{create:p.conditions},actions:{create:p.actions}} ,include:{conditions:true,actions:true}}));}catch(e){jsonError(res,e)}});
router.get('/bots/:botId/automations/:automationId',async(req:AuthRequest,res)=>{const a=await ownerAutomation(req.user!.id,req.params.botId,req.params.automationId);if(!a)return res.sendStatus(404);res.json(a);});
router.patch('/bots/:botId/automations/:automationId',async(req:AuthRequest,res)=>{const a=await ownerAutomation(req.user!.id,req.params.botId,req.params.automationId);if(!a)return res.sendStatus(404);try{const p=automationInput.partial().parse(req.body);const updated=await db.$transaction(async tx=>{if(p.conditions||p.actions){await tx.automationCondition.deleteMany({where:{automationId:a.id}});await tx.automationAction.deleteMany({where:{automationId:a.id}});}return tx.automation.update({where:{id:a.id},data:{name:p.name,enabled:p.enabled,trigger:p.trigger,cooldown:p.cooldown,executionLimit:p.executionLimit,maxDepth:p.maxDepth,conditions:p.conditions?{create:p.conditions}:undefined,actions:p.actions?{create:p.actions}:undefined},include:{conditions:true,actions:true}})});res.json(updated);}catch(e){jsonError(res,e)}});
router.delete('/bots/:botId/automations/:automationId',async(req:AuthRequest,res)=>{if(!await ownerAutomation(req.user!.id,req.params.botId,req.params.automationId))return res.sendStatus(404);await db.automation.delete({where:{id:req.params.automationId}});res.sendStatus(204);});
router.post('/bots/:botId/automations/:automationId/:operation',async(req:AuthRequest,res)=>{const a=await ownerAutomation(req.user!.id,req.params.botId,req.params.automationId);if(!a)return res.sendStatus(404);if(!['enable','disable','test'].includes(req.params.operation))return res.sendStatus(404);if(req.params.operation==='test'){res.json(await runAutomation(a,{type:a.trigger,manual:true}));}else res.json(await db.automation.update({where:{id:a.id},data:{enabled:req.params.operation==='enable'}}));});
router.get('/bots/:botId/automations/:automationId/executions',async(req:AuthRequest,res)=>{if(!await ownerAutomation(req.user!.id,req.params.botId,req.params.automationId))return res.sendStatus(404);res.json(await db.automationExecution.findMany({where:{automationId:req.params.automationId},orderBy:{createdAt:'desc'},take:200})});

router.get('/bots/:botId/schedules',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.schedule.findMany({where:{botId:req.params.botId},orderBy:{nextRunAt:'asc'}}));});
router.post('/bots/:botId/schedules',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);try{const p=scheduleInput.parse(req.body);const next=p.nextRunAt||new Date(Date.now()+Math.max(60000,(p.interval||1)*60000));res.status(201).json(await db.schedule.create({data:{...p,nextRunAt:next,botId:req.params.botId}}));}catch(e){jsonError(res,e)}});
router.patch('/bots/:botId/schedules/:scheduleId',async(req:AuthRequest,res)=>{if(!await ownerSchedule(req.user!.id,req.params.botId,req.params.scheduleId))return res.sendStatus(404);try{res.json(await db.schedule.update({where:{id:req.params.scheduleId},data:scheduleInput.partial().parse(req.body)}));}catch(e){jsonError(res,e)}});
router.delete('/bots/:botId/schedules/:scheduleId',async(req:AuthRequest,res)=>{if(!await ownerSchedule(req.user!.id,req.params.botId,req.params.scheduleId))return res.sendStatus(404);await db.schedule.delete({where:{id:req.params.scheduleId}});res.sendStatus(204);});
router.post('/bots/:botId/schedules/:scheduleId/:operation',async(req:AuthRequest,res)=>{const s=await ownerSchedule(req.user!.id,req.params.botId,req.params.scheduleId);if(!s)return res.sendStatus(404);if(req.params.operation==='run')return res.json(await runSchedule(s));if(!['enable','disable'].includes(req.params.operation))return res.sendStatus(404);res.json(await db.schedule.update({where:{id:s.id},data:{enabled:req.params.operation==='enable'}}));});

router.get('/notifications',async(req:AuthRequest,res)=>res.json(await db.notification.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'},take:200})));router.post('/notifications/:id/read',async(req:AuthRequest,res)=>{const n=await db.notification.updateMany({where:{id:req.params.id,userId:req.user!.id},data:{read:true}});res.json({updated:n.count});});router.post('/notifications/read-all',async(req:AuthRequest,res)=>{const n=await db.notification.updateMany({where:{userId:req.user!.id,read:false},data:{read:true}});res.json({updated:n.count});});router.delete('/notifications/:id',async(req:AuthRequest,res)=>{await db.notification.deleteMany({where:{id:req.params.id,userId:req.user!.id}});res.sendStatus(204);});
router.get('/bots/:botId/monitoring',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);res.json(await db.monitoringRecord.findFirst({where:{botId:b.id},orderBy:{recordedAt:'desc'}}));});router.get('/bots/:botId/monitoring/history',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.monitoringRecord.findMany({where:{botId:req.params.botId},orderBy:{recordedAt:'desc'},take:500})});
router.get('/bots/:botId/backups',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);res.json(await db.backup.findMany({where:{botId:req.params.botId},orderBy:{createdAt:'desc'},select:{id:true,label:true,createdAt:true,data:true}}));});
router.post('/bots/:botId/backups',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);if(!b)return res.sendStatus(404);const [automations,schedules,workflows,auth]=await Promise.all([db.automation.findMany({where:{botId:b.id},include:{conditions:true,actions:true}}),db.schedule.findMany({where:{botId:b.id}}),db.workflow.findMany({where:{botId:b.id}}),db.authConfig.findUnique({where:{botId:b.id},select:{type:true,autoLogin:true,loginCommand:true,registerCommand:true,loginTrigger:true,delay:true}})]);const data={bot:{name:b.name,username:b.username,minecraftVersion:b.minecraftVersion,edition:b.edition,autoReconnect:b.autoReconnect,maxRetries:b.maxRetries,reconnectDelay:b.reconnectDelay,startOnBoot:b.startOnBoot,settings:b.settings},server:{name:b.server.name,host:b.server.host,port:b.server.port,edition:b.server.edition,version:b.server.version,settings:b.server.settings},automations,schedules,workflows,auth};res.status(201).json(await db.backup.create({data:{botId:b.id,label:String(req.body?.label||'Manual backup'),data}}));});
router.post('/bots/:botId/backups/:backupId/restore',async(req:AuthRequest,res)=>{const b=await ownerBot(req.user!.id,req.params.botId);const backup=await db.backup.findFirst({where:{id:req.params.backupId,botId:req.params.botId,bot:{server:{userId:req.user!.id}}}});if(!b||!backup)return res.sendStatus(404);const data=backup.data as any;if(data.bot)await db.bot.update({where:{id:b.id},data:data.bot});res.json({restored:true});});router.delete('/bots/:botId/backups/:backupId',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);await db.backup.deleteMany({where:{id:req.params.backupId,botId:req.params.botId}});res.sendStatus(204);});
router.patch('/servers/:serverId/settings',async(req:AuthRequest,res)=>{if(!await ownerServer(req.user!.id,req.params.serverId))return res.sendStatus(404);const p=z.record(z.string(),z.unknown()).parse(req.body);res.json(await db.server.update({where:{id:req.params.serverId},data:{settings:p}}));});router.patch('/bots/:botId/settings',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);const p=z.record(z.string(),z.unknown()).parse(req.body);res.json(await db.bot.update({where:{id:req.params.botId},data:{settings:p}}));});router.put('/bots/:botId/auth-config',async(req:AuthRequest,res)=>{if(!await ownerBot(req.user!.id,req.params.botId))return res.sendStatus(404);const p=z.object({type:z.enum(['OFFLINE','MICROSOFT','LOGIN_PLUGIN','CUSTOM']),autoLogin:z.boolean().default(false),loginCommand:z.string().max(256).optional(),registerCommand:z.string().max(256).optional(),loginTrigger:z.string().max(256).optional(),delay:z.coerce.number().int().min(0).max(60000).default(1000),secret:z.string().max(1000).optional()}).parse(req.body);const {secret,...safe}=p;res.json(await db.authConfig.upsert({where:{botId:req.params.botId},create:{...safe,botId:req.params.botId,secretCiphertext:secret?encrypt(secret):undefined},update:{...safe,secretCiphertext:secret?encrypt(secret):undefined},select:{id:true,botId:true,type:true,autoLogin:true,loginCommand:true,registerCommand:true,loginTrigger:true,delay:true}}));});
router.get('/events',async(req:AuthRequest,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');const send=(e:any)=>res.write(`data: ${JSON.stringify(e)}\n\n`);realtime.on('event',send);req.on('close',()=>realtime.off('event',send));});
export default router;
